title: Dahyun Joo
author:
  name: Dahyun Joo
  email: clairda@snu.ac.kr
description: > # this means to ignore newlines until "show_excerpts:"
  I am a graduate student in the Department of Mechanical Engineering at Seoul National University, working at AISDL (AI-driven Simulation and Design Lab) under Prof. Do-Nyun Kim. 

show_excerpts: false # set to true to show excerpts on the homepage

permalink: /:title

url: "https://springfall137.github.io" # the base hostname & protocol for your site
  
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "" # G-XXXXXXXXXX
    anonymize_ip         : # true, false (default)

collections:
  publication:
    output: true

theme: minima
markdown: kramdown